### ISSUE TITLE
OrderServiceCriteria.PageNumberFilter doesn't work

### ISSUE THREAD

**Issue by RoarkDude** [skuvault/channelAdvisorAccess#3]
Setting the PageNumberFilter to a specific number doesn't work.  Looking at the code the GetOrders function set the PageNumberFilter to 1 and increments it  while calling GetOrdersPages.

**Comment by slav** [comment]
We've tested and it appears to work fine. Will close. If it's still an issue, please provide more details to allow us reproduce the issue.
